"""Initial tables

Revision ID: 2263e83a1637
Revises: 
Create Date: 2026-03-10 17:45:40.207231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2263e83a1637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_developer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['game_developer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('gamer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gamer_id')
    )
    op.create_table('gamer_game',
    sa.Column('gamer_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamer.id'], ),
    sa.PrimaryKeyConstraint('gamer_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamer_game')
    op.drop_table('profile')
    op.drop_table('game')
    op.drop_table('gamer')
    op.drop_table('game_developer')
    # ### end Alembic commands ###
